---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      gh-actions-dependencies:
        patterns: ['*']
    labels: [gh-actions, dependencies]
    commit-message:
      prefix: gh-actions
      include: scope
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    versioning-strategy: increase-if-necessary
    groups:
      python-dependencies:
        patterns: ['*']
    labels: [python, dependencies]
    commit-message:
      prefix: python-deps
      include: scope
