---
version: 2
multi-ecosystem-groups:
  python-and-pre-commit:
    schedule:
      interval: weekly
    labels: [python, pre-commit, dependencies]
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      gh-actions-dependencies:
        patterns: ['*']
    labels: [gh-actions, dependencies]
    commit-message:
      prefix: gh-actions
      include: scope
  - package-ecosystem: pip
    directory: /
    multi-ecosystem-group: python-and-pre-commit
    versioning-strategy: increase-if-necessary
    patterns: ['*']
    labels: [python, dependencies]
    commit-message:
      prefix: python-deps
      include: scope
  - package-ecosystem: pre-commit
    directory: /
    multi-ecosystem-group: python-and-pre-commit
    patterns: ['*']
    labels: [pre-commit, dependencies]
    commit-message:
      prefix: pre-commit-deps
      include: scope
