---
ignore:
  - vulnerability: GHSA-4xh5-x5gv-qwph
    reason: Ignored because it is a development dependency
  - vulnerability: GHSA-w853-jp5j-5j7f
    reason: Ignored until Python 3.9 support is removed
