---
version: 2
build:
  os: ubuntu-22.04
  tools:
    python: '3.11'  # This needs to stay in sync with the tox config in pyproject.toml and any CI scripts
    nodejs: '20'  # This needs to stay in sync with any CI scripts
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: true
