---
name: Bug Report
description: File a bug report here
title: '[BUG]: '
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to submit a bug report!
        Please make sure there aren't any open/closed issues for this topic already.
  - type: textarea
    id: bug-description
    attributes:
      label: Description of the bug
      description: Give us a brief description of what happened and what is the expected
        behavior
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: environment-information
    attributes:
      label: Environment Information
      description: |
        Please tell us about your environment:
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: |-
        Provide any additional information such as logs, screenshots, likes, scenarios in which the bug occurs so that it facilitates resolving the issue.
